title: "K책re Overg책rd's Blog"
description: "A blog about Microsoft infrastructure, identity management and automation."

theme: jekyll-theme-minimal
classes: wide

# Build settings
permalink: /:year/:title/

# Author settings
author:
  name     : "K책re Overg책rd"

exclude: ["Gemfile", "Gemfile.lock", "README.md", "LICENSE.txt"]