# Metadata
title: "& blog"
description: "A blog about Microsoft infrastructure, identity management and automation."
author:
  name: Kåre Overgård
  email: k@overgard.dk

# Needed plugins
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag

# Theme settings
remote_theme: "jekyll/minima@bf9ef98"  # Locked to a specific commit for stability
minima:
  skin: auto
  nav_pages:
    - about.md
  social_links:
    - title: GitHub profile
      icon: github
      url: "https://github.com/kovergard"
    - title: LinkedIn profile
      icon: linkedin
      url: "https://www.linkedin.com/in/kaareovergaard"
    - title: Portfolio site (Danish)
      icon: wordpress
      url: "https://overgard.dk"
  date_format: "%Y-%m-%d"
  show_excerpts: false

# Build settings
permalink: /:year/:title/
exclude: ["Gemfile", "Gemfile.lock", "README.md", "LICENSE.txt"]

